[tool.poetry]
name = "brendwall"
version = "0.1.0"
description = "env"
authors = ["ragecodemode <nikitaloskutov18@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
