# Generated by Django 5.1.1 on 2024-09-18 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.IntegerField(default=1, error_messages={'errors': 'Минимальное время готовки 1 минута.'}, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('title',),
            },
        ),
    ]
